[package]
name = "antof_traffic"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.3", features = ["runtime-tokio-native-tls", "postgres", "uuid"] }
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0.217", features = ["derive"] }
reqwest = { version = "0.12.12", features = ["blocking"] }
dotenv = "0.15.0"
serde_json = { version = "1.0.138" }
